[package]
name = "oxine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplelog = "0.12"
log = "0.4"
threadpool = "1"
serde = "1"
toml = "0.8"
once_cell = "1"
pollster = "0.3"