[package]
name = "oxine-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplelog = "0.12"
log = "0.4"
serde = "1"
serde_json = "1"
toml = "0.8"
once_cell = "1"
tokio = {version = "1", features = ["rt-multi-thread", "macros", "net", "time", "sync"] }
oxine = {path = "../lib"}
rand = "0.8"
reqwest = "0.12"
md5 = "0.7"
cfg-if = "1"
flate2 = "1"
